name: geodepth 
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.3.1
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - torchvision=0.19.0
  - lightning=2.4.0
  - numpy=2.2.0
  - matplotlib=3.10.0
  - imageio=2.36.1
  - pandas=2.2.3
  - ipykernel=6.29.5
  - pip:
    - tensorboard==2.18.0
